Hello_World/hello.c
=> Added Hello.c

imdb.py
IT IS A MINI-IMDB PROJECT THAT PROVIDES INFORMATION ABOUT ANY MOVIE OR TV SERIES WHEN SEARCHED.
This project is coded in python language and uses basics of python data structure - lists, OOPS and some basics of database.
Do remember to read the documentation at the top of the source code for smooth learning.
=> Automated movies and TV search using python scripts

Hello_World/hello.php
=> I am creating the file hello.php

hello.cpp
Added a new file named hello.cpp which can print Hello, World on execution
=> created hello.cpp

Hello_World/hello_World.java, Hello_World/hello_world.java
For Hacktoberfest 2020.
Please add "hacktoberfest-accepted" label
=> UPDATED hello world

Hello_World/hello.py, Projects/dadjokes.py
Hey there! I've added `dadjokes.py` into projects. This asynchronously fetches dad jokes using an API.
`hello.py` has an unnecessary variable assignment and can be reduced to one line for simplicity's sake
=> Async Dad Joke Fetching + Simplifying Hello World

Hello_World/hello.m
created a file to print hello world in MATLAB
=> CREATED hello.m

Projects/imdb.py
=> code and docs improved

Hello_World/README.md, Hello_World/hello.pl
Added the hello world in Perl programming language and added myself as a contributor in the README file
=> Add hello.pl and update readme

Projects/Python_Gui_Sorting.py
=> Gui Python Sorting

Hello_World/README.md
=> Add Relative Paths

mergesort.py
=> mergesort.py

Projects/bst_traversal1.cpp, bst_traversal.cpp
Please add this bst_traversal program to your repository
=> Added bst_traversal.cpp

Dev_Jokes_and_Quotes/README.md
Reverts aryangulati/Hacktoberfest2020#100
=> Revert "added my devjoke picture in readme of devjoke"

Projects/Chat_client_server/111708002/tcp_chat_client.py, Projects/Chat_client_server/111708002/tcp_chat_server.py
=> added chat (broadcast) client and server in python

Hello_World/hello.f90, Hello_World/hello.kt
I added the hello.f90 and I modified the hello.kt adding "args: Array<String>" which is better for bigger programs
=> new fortran hello file and modified kotlin hello file

Projects/MacSniffer_EthicalHacking/macsniffer.py, Projects/MacSniffer_EthicalHacking/readme.md
This folder contains mac sniffers that help you and your organization to know the mac address of the system your machine interacts with on the network..
This is an educational purpose python program which helps you to be alert from cyber attacks and expand your knowledge  
HAPPY HACKING AND STAY SAFE BY KNOWING YOUR WEAKNESSES
For hacktoberfest, do add hactoberfest accepted label for easy recognization
=> MacSniffer_EthicalHacking containg macsniffer.py for getting mac address on the network

Hello_World/Hello_World.hs
Reasons to revert and remove:
- Haskell is already added
- Please read contribution guidelines and name files accordingly.
=> Revert "Haskell Programming, Hello_World.hs"

Hello_World/hello.bat
=> add hello.bat

Hello_World/hello.dart
=> Added hello in DART.

Projects/recursiveLists.pl
Solves simple task like delete the first item of a list, check if are equal
=> Added a recursive program written in Prolog

Projects/ECommerce-python/CaseStudy-stmt.md, Projects/ECommerce-python/Customer.py, Projects/ECommerce-python/CustomerDataout.csv, Projects/ECommerce-python/CustomerNotAllowedException.py, Projects/ECommerce-python/FairDealCustomerData.csv, Projects/ECommerce-python/Orders.py, Projects/ECommerce-python/main.py, Projects/ECommerce-python/sample.py
Hi,
Added Python customer data handling and Integration - Ecommerce case study for having to practise working with datasets and files in python.
Also added datasets along with this.
Excited and wish to contribute more to this project.
Thanks.
=> Added Python customer datahandling - Ecommerce casestudy

Dev_Jokes_and_Quotes/README.md, Hello_World/README.md, Hello_World/hello.txt
program for printing hello world in BC programming language and a new joke added.
=> three more commits

Projects/quickSort.java
Added quick sort algorithm in java
=> quick sort

Pacman in cpp
Traditional Pacman game made in cpp
=> Create Pacman in cpp

Hello_World/HelloWorld.asm, Hello_World/README.md
Added file and updated reference in README.md
=> Added HelloWorld in Assembly language

Projects/simpleForm.js
add a JavaScript simple form.
Happy Hacktoberfest2020~~
=> simpleForm

Hello_World/Hello.cu
Hello World in CUDA
Hacktoberfest2021
=> Hello World in CUDA

Projects/Automate Chrome Dinosaur/dino.py
=> Initial Commit

Dev_Jokes_and_Quotes/README.md
Added quote
Hacktoberfest 2021
=> Added quote

Hello_World/hello.clj
Added hello.clj in hello world directory-program for clojure language
=> Add clojure hello world program

DataStructure_and_Algorithms/CPP/Dynamic Programming/subset_sum.cpp, DataStructure_and_Algorithms/CPP/Sorting/insertion_sort.cpp, Projects/snake_game.py
I have added insertion sort code in cpp language in Data_Structures_and_Algorithms folder.Comments are also added to enable beginners get the gist of topic.Please accept my pull request.
=> added insertion sort code in cpp

DataStructure_and_Algorithms/JAVA/String/Longest_Substring_With_Distinct_Characters.java
This programs finds the length of the longest substring without repeating characters. 
For Example :  For “ABDEFGABEF”, the longest substring are “BDEFGA” and “DEFGAB”, with length 6.
=> Add LongestSubStringWithDistinctCharacters in java

DataStructure_and_Algorithms/Python/Recursion/Permutations of given array.py
This pull request adds recursive Python 3 program to generate all possible permutations of a given numbers array. The program is stored under the DataStructure_and_Algorithms/Python/Recursion directory and is typed as well as commented. Please have a look, and let me know if any updations are required in it.
=> Add recursive Python 3 Permutations program

Projects/alarm_clock.py
=> Alarm clock In python

DataStructure_and_Algorithms/Go/bubble_sort.go, DataStructure_and_Algorithms/Go/merge_sort.go, DataStructure_and_Algorithms/Python/Sorting/bubble_sort.py, DataStructure_and_Algorithms/Python/Sorting/merge_sort.py
Linked with https://github.com/aryangulati/DEV/issues/247
Please suggest any valuable feedback if any.
=> Merge sort and bubble sort in python and golang
